import { SearchParameters, UuidViewModel } from '@/interfaces/api';
import { ShipRoleReference } from '@/interfaces/constructions/shipRoleReference';

export interface ShipSearchParameters extends SearchParameters {
    companyIds?: string | null;
    creatorIds?: string | null;
    shipRoleIds?: string | null;
    armorMaterialIds: string | null;
    minOreCrates?: number | null;
    maxOreCrates?: number | null;
    minSpeedWithoutCargo?: number | null;
    maxSpeedWithoutCargo?: number | null;
    minSpeedWithCargo?: number | null;
    maxSpeedWithCargo?: number | null;
    minPriceBlueprint?: number | null;
    maxPriceBlueprint?: number | null;
    minPriceShip?: number | null;
    maxPriceShip?: number | null;
    minResourceBridges?: number | null;
    maxResourceBridges?: number | null;
    minBatteries?: number | null;
    maxBatteries?: number | null;
    minGeneratedPower?: number | null;
    maxGeneratedPower?: number | null;
    minPropellantCapacity?: number | null;
    maxPropellantCapacity?: number | null;
    minBackwardThrustPower?: number | null;
    maxBackwardThrustPower?: number | null;
    minForwardThrustPower?: number | null;
    maxForwardThrustPower?: number | null;
    minLength?: number | null;
    maxLength?: number | null;
    minHeight?: number | null;
    maxHeight?: number | null;
    minWidth?: number | null;
    maxWidth?: number | null;
    minFlightTime?: number | null;
    maxFlightTime?: number | null;
    minTotalMassWithoutCargo?: number | null;
    maxTotalMassWithoutCargo?: number | null;
    minRadiators?: number | null;
    maxRadiators?: number | null;
    minMiningLasers?: number | null;
    maxMiningLasers?: number | null;
    minOreCollectors?: number | null;
    maxOreCollectors?: number | null;
    minPrimaryWeaponsAutoCannons?: number | null;
    maxPrimaryWeaponsAutoCannons?: number | null;
    minPrimaryWeaponsLaserCannons?: number | null;
    maxPrimaryWeaponsLaserCannons?: number | null;
    minPrimaryWeaponsPlasmaCannons?: number | null;
    maxPrimaryWeaponsPlasmaCannons?: number | null;
    minPrimaryWeaponsRailCannons?: number | null;
    maxPrimaryWeaponsRailCannons?: number | null;
    minPrimaryWeaponsMissileLauncher?: number | null;
    maxPrimaryWeaponsMissileLauncher?: number | null;
    minPrimaryWeaponsTorpedoLauncher?: number | null;
    maxPrimaryWeaponsTorpedoLauncher?: number | null;
    minTurretWeaponsAutoCannons?: number | null;
    maxTurretWeaponsAutoCannons?: number | null;
    minTurretWeaponsLaserCannons?: number | null;
    maxTurretWeaponsLaserCannons?: number | null;
    minTurretWeaponsPlasmaCannons?: number | null;
    maxTurretWeaponsPlasmaCannons?: number | null;
    minTurretWeaponsRailCannons?: number | null;
    maxTurretWeaponsRailCannons?: number | null;
    minTurretWeaponsMissileLauncher?: number | null;
    maxTurretWeaponsMissileLauncher?: number | null;
    minTurretWeaponsTorpedoLauncher?: number | null;
    maxTurretWeaponsTorpedoLauncher?: number | null;
}

export interface Ship extends UuidViewModel {
    companyId: string | null;
    creatorId: string | null;
    armorMaterialId: string | null;
    name: string;
    description: string;
    previewImageUri: string;
    imageUris: string | null;
    youtubeVideoUri: string | null;
    oreCrates: number | null;
    speedWithoutCargo: number | null;
    speedWithCargo: number | null;
    priceBlueprint: number | null;
    priceShip: number | null;
    resourceBridges: number | null;
    batteries: number | null;
    generatedPower: number | null;
    propellantCapacity: number | null;
    backwardThrustPower: number | null;
    forwardThrustPower: number | null;
    length: number | null;
    height: number | null;
    width: number | null;
    flightTime: number | null;
    totalMassWithoutCargo: number | null;
    radiators: number | null;
    miningLasers: number | null;
    oreCollectors: number | null;
    primaryWeaponsAutoCannons: number | null;
    primaryWeaponsLaserCannons: number | null;
    primaryWeaponsPlasmaCannons: number | null;
    primaryWeaponsRailCannons: number | null;
    primaryWeaponsMissileLauncher: number | null;
    primaryWeaponsTorpedoLauncher: number | null;
    turretWeaponsAutoCannons: number | null;
    turretWeaponsLaserCannons: number | null;
    turretWeaponsPlasmaCannons: number | null;
    turretWeaponsRailCannons: number | null;
    turretWeaponsMissileLauncher: number | null;
    turretWeaponsTorpedoLauncher: number | null;
    shipRoles: ShipRoleReference[];
}

export interface CreateShip {
    companyId?: string | null;
    armorMaterialId?: string | null;
    name: string;
    description: string;
    previewImageUri: string;
    imageUris?: string | null;
    youtubeVideoUri?: string | null;
    oreCrates?: number | null;
    speedWithoutCargo?: number | null;
    speedWithCargo?: number | null;
    priceBlueprint?: number | null;
    priceShip?: number | null;
    resourceBridges?: number | null;
    batteries?: number | null;
    generatedPower?: number | null;
    propellantCapacity?: number | null;
    backwardThrustPower?: number | null;
    forwardThrustPower?: number | null;
    length?: number | null;
    height?: number | null;
    width?: number | null;
    flightTime?: number | null;
    totalMassWithoutCargo?: number | null;
    radiators?: number | null;
    miningLasers?: number | null;
    oreCollectors?: number | null;
    primaryWeaponsAutoCannons?: number | null;
    primaryWeaponsLaserCannons?: number | null;
    primaryWeaponsPlasmaCannons?: number | null;
    primaryWeaponsRailCannons?: number | null;
    primaryWeaponsMissileLauncher?: number | null;
    primaryWeaponsTorpedoLauncher?: number | null;
    turretWeaponsAutoCannons?: number | null;
    turretWeaponsLaserCannons?: number | null;
    turretWeaponsPlasmaCannons?: number | null;
    turretWeaponsRailCannons?: number | null;
    turretWeaponsMissileLauncher?: number | null;
    turretWeaponsTorpedoLauncher?: number | null;
    shipRoleIds: string[];
    isCreator?: boolean;
}

export interface PatchShip {
    companyId?: string | null;
    armorMaterialId?: string | null;
    name?: string;
    description?: string;
    previewImageUri?: string;
    imageUris?: string | null;
    youtubeVideoUri?: string | null;
    oreCrates?: number | null;
    speedWithoutCargo?: number | null;
    speedWithCargo?: number | null;
    priceBlueprint?: number | null;
    priceShip?: number | null;
    resourceBridges?: number | null;
    batteries?: number | null;
    generatedPower?: number | null;
    propellantCapacity?: number | null;
    backwardThrustPower?: number | null;
    forwardThrustPower?: number | null;
    length?: number | null;
    height?: number | null;
    width?: number | null;
    flightTime?: number | null;
    totalMassWithoutCargo?: number | null;
    radiators?: number | null;
    miningLasers?: number | null;
    oreCollectors?: number | null;
    primaryWeaponsAutoCannons?: number | null;
    primaryWeaponsLaserCannons?: number | null;
    primaryWeaponsPlasmaCannons?: number | null;
    primaryWeaponsRailCannons?: number | null;
    primaryWeaponsMissileLauncher?: number | null;
    primaryWeaponsTorpedoLauncher?: number | null;
    turretWeaponsAutoCannons?: number | null;
    turretWeaponsLaserCannons?: number | null;
    turretWeaponsPlasmaCannons?: number | null;
    turretWeaponsRailCannons?: number | null;
    turretWeaponsMissileLauncher?: number | null;
    turretWeaponsTorpedoLauncher?: number | null;
    shipRoleIds?: string[];
}

export interface ShipCreatorAssignment {
    creatorId: string | null;
}
